baseURL = "https://arslankhanali.github.io/mysite/"
title = "Arslan's Docs & Blog"
theme = "hugo-book"
defaultContentLanguage = "en"


[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
  BookSection = "docs"
  BookMenuBundle = "/docs"
  BookRepo = "https://github.com/arslankhanali/mysite"
  BookLogo = "favicon.ico"
  BookToC = true
  BookSearch = true

# [menu]
# [[menu.before]]
#   name = "Docs"
#   url = "/docs/"
#   weight = 1
#
# [[menu.before]]
#   name = "Blog"
#   url = "/posts/"
#   weight = 2
